# Generated by Django 3.1.2 on 2021-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210422_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Genoise Cake', 'Genoise Cake'), ('Angel Food Cake', 'Angel Food Cake'), ('Biscuit Cake', 'Biscuit Cake'), ('Pound Cake', 'Pound Cake'), ('Sponge Cake', 'Sponge Cake'), ('Chiffon Cake', 'Chiffon Cake'), ('Baked Flourless Cake', 'Baked Flourless Cake'), ('Carrot Cake', 'Carrot Cake')], max_length=50, null=True),
        ),
    ]
